### ISSUE TITLE
Error when upgrading Adapty 1.4.0

### ISSUE THREAD

**Issue by huseyintamer** [adaptyteam/AdaptySDK-React-Native#35]
Dependencies
```
    "react-native-adapty": "^1.4.0",
    "react": "18.1.0",
    "react-native": "0.70.0",
```
Kotlin version (it's worked on  adapty v1.3.13)

`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"`

Error message

```
> Task :lottie-react-native:compileDebugJavaWithJavac

> Task :notifee_react-native:compileDebugJavaWithJavac

> Task :react-native-adapty:compileDebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
402 actionable tasks: 382 executed, 20 up-to-date
Note: /Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/react-native-adapty/lib/android/src/main/java/com/rnadapty/react/models/AdaptyRNError.kt: (18, 75): Cannot access 'value': it is internal in 'AdaptyErrorCode'
e: /Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/react-native-adapty/lib/android/src/main/java/com/rnadapty/react/models/AdaptyRNError.kt: (46, 37): Cannot access 'value': it is internal in 'AdaptyErrorCode'

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-adapty:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUİLD FAILED in 29s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/react-native-adapty/lib/android/src/main/java/com/rnadapty/react/models/AdaptyRNError.kt: (18, 75): Cannot access 'value': it is internal in 'AdaptyErrorCode'
e: /Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/react-native-adapty/lib/android/src/main/java/com/rnadapty/react/models/AdaptyRNError.kt: (46, 37): Cannot access 'value': it is internal in 'AdaptyErrorCode'

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-adapty:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUİLD FAILED in 29s

    at makeError (/Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/execa/index.js:174:9)
    at /Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/huseyintamer/Desktop/Hiface/Software/Hiface/node_modules/@react-native-community/cli/build/index.js:142:9)

```
_I look forward to your help, thank you._

**Comment by msahajwani** [comment]
+1

**Comment by divanc** [comment]
Hey! Looking into this...

**Comment by divanc** [comment]
Found a bug, please update to v1.4.1 to fix this issue.
---

If you are curious I will append some explanations below.
My test case for Android Adapty stayed on previous android version (v1.9.0) instead of a new one (v1.12.0), it turned out deep-copying to node_modules does not seem to work for android dependencies

**Comment by huseyintamer** [comment]
Resolved Thanks @divanc 🤙🏻
